...
======================================================================
FAIL: test_client_decodeemote (__main__.TestBufServer) [No Address/Leak Sanitizer errors should occur]
Client should correctly decode and display emote.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "client_subtests.py", line 258, in test_client_decodeemote
    self.assertNotIn(b"Sanitizer", c1err)
AssertionError: b'Sanitizer' unexpectedly found in b'=================================================================\n==32181==ERROR: AddressSanitizer: attempting double-free on 0x603000000010 in thread T0:\n    #0 0x7f3411eac7a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)\n    #1 0x56371522fabe in main /csc209-w20/tutorials/w20/mark_a4/chat_client.c:704\n    #2 0x7f34119feb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\n    #3 0x56371522bb39 in _start (/csc209-w20/tutorials/w20/mark_a4/chat_client+0x2b39)\n\n0x603000000010 is located 0 bytes inside of 23-byte region [0x603000000010,0x603000000027)\nfreed by thread T0 here:\n    #0 0x7f3411eac7a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)\n    #1 0x56371522f95b in main /csc209-w20/tutorials/w20/mark_a4/chat_client.c:695\n    #2 0x7f34119feb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\n\npreviously allocated by thread T0 here:\n    #0 0x7f3411eacb40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)\n    #1 0x5637152303f6 in get_message /csc209-w20/tutorials/w20/mark_a4/socket.c:134\n    #2 0x56371522fa83 in main /csc209-w20/tutorials/w20/mark_a4/chat_client.c:546\n    #3 0x7f34119feb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\n\nSUMMARY: AddressSanitizer: double-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8) in __interceptor_free\n==32181==ABORTING\n'

======================================================================
FAIL: test_two_clients (__main__.TestBufServer) [Client 2 should receive message from client 1]
Two clients connect to server and send messages to each other.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "client_subtests.py", line 88, in test_two_clients
    self.assertIn(b'test message 1', c2out)
AssertionError: b'test message 1' not found in b'Please enter a username: '

======================================================================
FAIL: test_two_clients (__main__.TestBufServer) [Client 1 should receive message from client 2]
Two clients connect to server and send messages to each other.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "client_subtests.py", line 91, in test_two_clients
    self.assertIn(b'test message 2', c1out)
AssertionError: b'test message 2' not found in b'Please enter a username: '

======================================================================
FAIL: test_two_clients (__main__.TestBufServer) [Client 2 should prints message in correct format (e.g., colon after username, LF-terminated message]
Two clients connect to server and send messages to each other.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "client_subtests.py", line 94, in test_two_clients
    self.assertIn(b'user1: test message 1\n', c2out)
AssertionError: b'user1: test message 1\n' not found in b'Please enter a username: '

======================================================================
FAIL: test_two_clients (__main__.TestBufServer) [Client 1 should print message in correct format (e.g., colon after username, LF-terminated message]
Two clients connect to server and send messages to each other.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "client_subtests.py", line 97, in test_two_clients
    self.assertIn(b'user2: test message 2\n', c1out)
AssertionError: b'user2: test message 2\n' not found in b'Please enter a username: '

======================================================================
FAIL: test_two_clients (__main__.TestBufServer) [No Address/Leak Sanitizer errors should occur]
Two clients connect to server and send messages to each other.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "client_subtests.py", line 103, in test_two_clients
    self.assertNotIn(b"Sanitizer", c1err)
AssertionError: b'Sanitizer' unexpectedly found in b'=================================================================\n==32195==ERROR: AddressSanitizer: attempting double-free on 0x603000000010 in thread T0:\n    #0 0x7f387b0f87a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)\n    #1 0x561ac270fabe in main /csc209-w20/tutorials/w20/mark_a4/chat_client.c:704\n    #2 0x7f387ac4ab96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\n    #3 0x561ac270bb39 in _start (/csc209-w20/tutorials/w20/mark_a4/chat_client+0x2b39)\n\n0x603000000010 is located 0 bytes inside of 23-byte region [0x603000000010,0x603000000027)\nfreed by thread T0 here:\n    #0 0x7f387b0f87a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)\n    #1 0x561ac270efcc in main /csc209-w20/tutorials/w20/mark_a4/chat_client.c:584\n    #2 0x7f387ac4ab96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\n\npreviously allocated by thread T0 here:\n    #0 0x7f387b0f8b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)\n    #1 0x561ac27103f6 in get_message /csc209-w20/tutorials/w20/mark_a4/socket.c:134\n    #2 0x561ac270fa83 in main /csc209-w20/tutorials/w20/mark_a4/chat_client.c:546\n    #3 0x7f387ac4ab96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)\n\nSUMMARY: AddressSanitizer: double-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8) in __interceptor_free\n==32195==ABORTING\n'

----------------------------------------------------------------------
Ran 5 tests in 2.948s

FAILED (failures=6)
