F...F.....
======================================================================
FAIL: test_badname_error (__main__.TestBufServer)
Test to see if server sends back correct error message when client connects with bad name.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_test.py", line 234, in test_badname_error
    self.assertTrue(cstatus == 0, "Ensure that test client terminated successfully")
AssertionError: False is not true : Ensure that test client terminated successfully

======================================================================
FAIL: test_long_msg (__main__.TestBufServer)
Client sends excessively long message
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_test.py", line 149, in test_long_msg
    self.assertTrue(cstatus == 0, "Ensure that test client terminated successfully")
AssertionError: False is not true : Ensure that test client terminated successfully

----------------------------------------------------------------------
Ran 10 tests in 4.662s

FAILED (failures=2)
